#!/usr/bin/env sh

##############################################################################
# KAIVO note:
#
# This is NOT the official self-bootstrapping Gradle wrapper script (the one
# normally generated by `gradle wrapper`, which downloads and pins an exact
# Gradle version via gradle-wrapper.jar). That jar is a binary file and could
# not be produced in the environment this project was generated in.
#
# Instead, this script simply forwards every argument to whatever `gradle`
# is already installed and on PATH. That means:
#   - It works fine in CI environments that install Gradle themselves before
#     calling ./gradlew (this repo's GitHub Actions workflow does exactly
#     that via gradle/actions/setup-gradle).
#   - It works fine on any machine (or Codespace/Gitpod) that already has
#     Gradle installed, e.g. `sudo apt install gradle` or via sdkman.
#   - It will fail with "gradle: command not found" on a machine with no
#     Gradle installed at all and no CI step installing one first.
#
# If you want the real, official wrapper (recommended once you have internet
# access from a normal dev machine), just run this once from the project
# root and it will replace these files with the genuine ones:
#     gradle wrapper --gradle-version 8.7
##############################################################################

if ! command -v gradle >/dev/null 2>&1; then
  echo "error: 'gradle' was not found on PATH." >&2
  echo "This project ships a lightweight gradlew stand-in (see comment at the" >&2
  echo "top of this file) that requires a system Gradle install. Install" >&2
  echo "Gradle first, or run this in a CI job that installs it for you." >&2
  exit 1
fi

exec gradle "$@"
